//
//  LoginPresenter.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 09.08.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class LoginPresenter {

    // MARK: - Protocol properties
    weak var view: LoginViewInput?
    private var interactor: LoginInteractorInput
    private let router: LoginRouterInput

    // MARK: - Properties

    // MARK: - Init
    init(interactor: LoginInteractorInput, router: LoginRouterInput) {
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - LoginViewOutput
extension LoginPresenter: LoginViewOutput {

    func viewDidLoad() {
        view?.setupScreen(with: LoginViewModel())
    }

}

// MARK: - LoginInteractorOutput
extension LoginPresenter: LoginInteractorOutput {
    
}

