//
//  HumanProfileBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 19.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class HumanProfileBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - HumanProfileBuilderProtocol
extension HumanProfileBuilder: HumanProfileBuilderProtocol {

    static func build(with user: AppUser) -> HumanProfileViewController {
        let interactor = HumanProfileInteractor(userService: DIContainer.userService,
                                                firestoreService: DIContainer.firestoreService)
        let router = HumanProfileRouter()
        let presenter = HumanProfilePresenter(interactor: interactor, router: router, user: user)
        let viewController = HumanProfileViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
