//
//  AuthBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 01.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class AuthBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - AuthBuilderProtocol
extension AuthBuilder:AuthBuilderProtocol {

    static func build() -> AuthViewController {
        let interactor = AuthInteractor(authService: DIContainer.authService,
                                        firestoreService: DIContainer.firestoreService)
        let router = AuthRouter()
        let presenter = AuthPresenter(interactor: interactor, router: router)
        let viewController = AuthViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
