//
//  SignUpBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 03.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class SignUpBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - SignUpBuilderProtocol
extension SignUpBuilder: SignUpBuilderProtocol {

    static func build(with context: SignUpContext) -> SignUpViewController {
        let interactor = SignUpInteractor()
        let router = SignUpRouter()
        let presenter = SignUpPresenter(interactor: interactor, router: router, context: context)
        let viewController = SignUpViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}

struct SignUpContext {

    let authModule: AuthModuleInput

}
