//
//  SignUpPresenter.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 03.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class SignUpPresenter {

    // MARK: - Protocol properties
    weak var view: SignUpViewInput?
    private var interactor: SignUpInteractorInput
    private let router: SignUpRouterInput

    // MARK: - Properties

    // MARK: - Init
    init(interactor: SignUpInteractorInput, router: SignUpRouterInput) {
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - SignUpViewOutput
extension SignUpPresenter: SignUpViewOutput {
    func viewDidLoad() {}
}

// MARK: - SignUpInteractorOutput
extension SignUpPresenter: SignUpInteractorOutput {
    
}

