//
//  ChatsBuilder.swift
//  VitaChat
//
//  Created Vitaly on 13.01.2021.
//  Copyright © 2021 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class ChatsBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - ChatsBuilderProtocol
extension ChatsBuilder:ChatsBuilderProtocol {

    static func build(with user: AppUser) -> ChatsViewController {
        let interactor = ChatsInteractor()
        let router = ChatsRouter()
        let presenter = ChatsPresenter(interactor: interactor, router: router)
        let viewController = ChatsViewController(output: presenter, user: user)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
