//
//  ChatRequestBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 20.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class ChatRequestBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - ChatRequestBuilderProtocol
extension ChatRequestBuilder: ChatRequestBuilderProtocol {

    static func build(with context: ChatRequestContext) -> ChatRequestViewController {
        let interactor = ChatRequestInteractor()
        let router = ChatRequestRouter()
        let presenter = ChatRequestPresenter(interactor: interactor, router: router, context: context)
        let viewController = ChatRequestViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}

struct ChatRequestContext {

    let chat: AppChat
    let conversationModule: ConversationsModuleInput

}
