//
//  ConversationsBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 11.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class ConversationsBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - ConversationsBuilderProtocol
extension ConversationsBuilder: ConversationsBuilderProtocol {

    static func build(with user: AppUser) -> ConversationsViewController {
        let interactor = ConversationsInteractor(listenerService: DIContainer.listenerService,
                                                 userService: DIContainer.userService,
                                                 firestoreService: DIContainer.firestoreService)
        let router = ConversationsRouter()
        let presenter = ConversationsPresenter(interactor: interactor, router: router, currentUser: user)
        let viewController = ConversationsViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
