//
//  LoginBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 09.08.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class LoginBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - LoginBuilderProtocol
extension LoginBuilder: LoginBuilderProtocol {

    static func build() -> LoginViewController {
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter = LoginPresenter(interactor: interactor, router: router)
        let viewController = LoginViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
