//
//  PeopleBuilder.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 17.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Okhrimenko Vitaly @vitys96
//  https://github.com/vitys96/VIPER-module
//

final class PeopleBuilder {

    // MARK: - Init
    private init() {}

}

// MARK: - PeopleBuilderProtocol
extension PeopleBuilder: PeopleBuilderProtocol {

    static func build(with currentUser: AppUser) -> PeopleViewController {
        let interactor = PeopleInteractor(userService: DIContainer.userService,
                                          firestoreService: DIContainer.firestoreService)
        let router = PeopleRouter()
        let presenter = PeoplePresenter(interactor: interactor, router: router, currentUser: currentUser)
        let viewController = PeopleViewController(output: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.view = viewController

        return viewController
    }

}
