//
//  AuthPresenter.swift
//  VitaChat
//
//  Created Okhrimenko Vitaliy on 01.05.2020.
//  Copyright © 2020 Okhrimenko Vitaliy. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import GoogleSignIn
import Firebase
import UIKit

final class AuthPresenter {

    // MARK: - Protocol properties
    weak var view: AuthViewInput?
    private var interactor: AuthInteractorInput
    private let router: AuthRouterInput

    // MARK: - Properties

    // MARK: - Init
    init(interactor: AuthInteractorInput, router: AuthRouterInput) {
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - AuthViewOutput
extension AuthPresenter: AuthViewOutput {

    func didTapSignUpButton() {
        let context = SignUpContext(authModule: self)
        router.navigateToSignUpScreen(with: context)
    }

    func didTapLoginButton() {
        router.navigateToLoginScreen()
    }

    func didSigned(user: GIDGoogleUser, withError error: Error?) {
        guard let _ = error else {
            view?.startLoadingAnimation()
            interactor.userAuthByGoogle(user: user, withError: error)
            return
        }
    }

    func viewDidLoad() {}
}

// MARK: - AuthInteractorOutput
extension AuthPresenter: AuthInteractorOutput {

    func userDidExistInDB(user: AppUser) {
        view?.stopLoadingAnimation()
        router.navigateToMainTabBar(with: user)
    }

    func userDidNotExistInDB(user: User) {
        view?.stopLoadingAnimation()
        router.navigateToProfile(with: user)
    }
    
}

// MARK: - AuthModuleInput
extension AuthPresenter: AuthModuleInput {

    func didTapHasExistingAccount() {
        router.navigateToLoginScreen()
    }

}

